language: csharp
dist: bionic
mono: none
include:
- os: linux
dotnet: 3.0.100
sudo: false
script:
 - dotnet restore ./src/
 - dotnet build ./src/
 - dotnet test ./src/Protsyk.RayTracer.Challenge.UnitTests/
