language: csharp
dist: xenial
mono: none
include:
- os: linux
dotnet: 3.1
sudo: false
script:
 - dotnet restore ./src/
 - dotnet build ./src/
 - dotnet test ./src/Protsyk.RayTracer.Challenge.Core.UnitTests/
 - dotnet test ./src/Protsyk.RayTracer.Challenge.UnitTests/
